version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - nginx-proxy
  app:
    image: awsdevopro/apache-php56
    container_name: www.somarpon.com
    volumes:
      - ./public:/var/www/html
    environment:
      - VIRTUAL_HOST: somarpon.com,www.somarpon.com,app.somarpon.com,git.somarpon.com,pf.somarpon.com
      - LETSENCRYPT_HOST: somarpon.com,www.somarpon.com,app.somarpon.com,git.somarpon.com,pf.somarpon.com
      - LETSENCRYPT_EMAIL: awsdevopro@gmail.com
  
