version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:ro"
      - "./volumes/vhost.d:/etc/nginx/vhost.d"
      - "./volumes/html:/usr/share/nginx/html"
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/certs:/etc/nginx/certs:rw"
      - "./volumes/vhost.d:/etc/nginx/vhost.d"
      - "./volumes/html:/usr/share/nginx/html"
  somewebsite:
    image: nginx
    volumes:
      # specify your public html here
      - ./public:/usr/local/nginx/html
      # specify your conf here
    #  - ../somewebsite.com/conf:/etc/nginx/conf.d:ro
    environment:
      - VIRTUAL_HOST=somarpon.com,www.somarpon.com
      - LETSENCRYPT_HOST=somarpon.com,www.somarpon.com
      - LETSENCRYPT_EMAIL=awsdevopro@gmail.com
  